name: Build and Deploy

on:
  push:
    branches:
      - www

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install Node.JS
        uses: actions/setup-node@v1
        with:
          node-version: '16.3.0'

      - name: Restore node_modules cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: v2-${{ runner.os }}-${{steps.versions.outputs.node_version}}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            v2-${{ runner.os }}-${{steps.versions.outputs.node_version}}-yarn-

      - name: Install Javascript dependencies
        run: yarn install --immutable

      - name: Build website
        run: bundle exec middleman build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: master # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
